import Foundation

// MARK: - AdvisorCategory

/// Category of writing advice
public enum AdvisorCategory: String, Codable, CaseIterable, Equatable {
    case productivity
    case creativity
    case consistency
    case craft
    case goals

    public var displayName: String {
        switch self {
        case .productivity: return "Productivity"
        case .creativity: return "Creativity"
        case .consistency: return "Consistency"
        case .craft: return "Craft"
        case .goals: return "Goals"
        }
    }
}

// MARK: - AdvisorPriority

/// Priority level of an advisor recommendation
public enum AdvisorPriority: String, Codable, CaseIterable, Equatable {
    case high
    case medium
    case low
}

// MARK: - AdvisorRecommendation

/// A single personalized writing recommendation generated by the advisor
public struct AdvisorRecommendation: Codable, Identifiable, Equatable {
    public let id: UUID
    public let category: AdvisorCategory
    public let priority: AdvisorPriority
    public let title: String
    public let recommendation: String
    public let actionableSteps: [String]
    public let generatedAt: Date

    public init(
        id: UUID = UUID(),
        category: AdvisorCategory,
        priority: AdvisorPriority,
        title: String,
        recommendation: String,
        actionableSteps: [String],
        generatedAt: Date = Date()
    ) {
        self.id = id
        self.category = category
        self.priority = priority
        self.title = title
        self.recommendation = recommendation
        self.actionableSteps = actionableSteps
        self.generatedAt = generatedAt
    }
}

// MARK: - WritingAdvisorReport

/// A full advisor report containing ranked recommendations and an overall assessment
public struct WritingAdvisorReport: Codable, Equatable {
    public let recommendations: [AdvisorRecommendation]
    public let overallAssessment: String
    public let focusArea: AdvisorCategory
    public let generatedAt: Date

    public init(
        recommendations: [AdvisorRecommendation],
        overallAssessment: String,
        focusArea: AdvisorCategory,
        generatedAt: Date = Date()
    ) {
        self.recommendations = recommendations
        self.overallAssessment = overallAssessment
        self.focusArea = focusArea
        self.generatedAt = generatedAt
    }
}

// MARK: - AdvisorContext

/// Snapshot of the writer's current context passed to the advisor for generating advice
public struct AdvisorContext {
    public let totalDocuments: Int
    public let recentDocumentTitles: [String]
    public let totalWordsAcrossDocuments: Int
    public let documentCategories: [String]
    public let sessionStats: SessionStats?
    public let additionalNotes: String?

    public init(
        totalDocuments: Int,
        recentDocumentTitles: [String],
        totalWordsAcrossDocuments: Int,
        documentCategories: [String],
        sessionStats: SessionStats?,
        additionalNotes: String? = nil
    ) {
        self.totalDocuments = totalDocuments
        self.recentDocumentTitles = recentDocumentTitles
        self.totalWordsAcrossDocuments = totalWordsAcrossDocuments
        self.documentCategories = documentCategories
        self.sessionStats = sessionStats
        self.additionalNotes = additionalNotes
    }
}
